AKD/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings 

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    # url(r'^$', 'AKD.views.home', name='home'),
    url(r'^', include('landing.urls', namespace='landing')),
    url(r'^accesorios/', include('accesorios.urls', namespace='accesorios')),
    url(r'^juguetes/', include('juguetes.urls', namespace='juguetes')),
    url(r'^admin/', include(admin.site.urls)),
)
if settings.DEBUG:
	urlpatterns += patterns('',
		url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
		url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
	)

accesorios/urls.py
from django.conf.urls import url, patterns
from accesorios import views

urlpatterns = patterns('',
		url(r'^lista/$', views.lista, name='lista'),
		url(r'^lista/correas/$', views.lista_correas, name='lista_correas'),
		url(r'^lista/pecheras/$', views.lista_pecheras, name='lista_pecheras'),
		url(r'^lista/collares/$', views.lista_collares, name='lista_collares'),
		url(r'^lista/chalecos/$', views.lista_chalecos, name='lista_chalecos'),
		url(r'^detalle/correas/(?P<id_correa>[\d]+)/$', views.detalle_correa, name='detalle_correa'),
		url(r'^detalle/pecheras/(?P<id_pechera>[\d]+)/$', views.detalle_pechera, name='detalle_pechera'),
		url(r'^detalle/collares/(?P<id_collar>[\d]+)/$', views.detalle_collar, name='detalle_collar'),
		url(r'^detalle/chalecos/(?P<id_chaleco>[\d]+)/$', views.detalle_chaleco, name='detalle_chaleco'),
	)

juguetes/urls.py
from django.conf.urls import url, patterns
from juguetes import views

urlpatterns = patterns('',
	url(r'^lista/$', views.lista, name='lista'),
	url(r'^lista/pelotas$', views.lista_pelotas, name='lista_pelotas'),
	url(r'^detalle/pelotas/(?P<id_pelota>[\d]+)/$', views.detalle_pelota, name='detalle_pelota'),
)

landing/urls.py
from django.conf.urls import url, patterns
from landing import views

urlpatterns = patterns('',
		url(r'^$', views.home, name='home'),
		url(r'^contacto/$', views.contacto, name='contacto'),
		url(r'^contactar/$', views.contactar, name='contactar')
	)

landing/models.py
from django.db import models

# Create your models here.

landing/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from accesorios.models import Correa, Chaleco, Pechera, Collar
from juguetes.models import Pelota

def home(request):
	correas = Correa.objects.order_by('-fecha_creacion')[:4]
	pecheras = Pechera.objects.order_by('-fecha_creacion')[:4]
	chalecos = Chaleco.objects.order_by('-fecha_creacion')[:4]
	collares = Collar.objects.order_by('-fecha_creacion')[:4]
	pelotas = Pelota.objects.order_by('-fecha_creacion')[:4]
	context = {
		'correas':correas,
		'pecheras':pecheras,
		'chalecos':chalecos,
		'collares':collares,
		'pelotas':pelotas,
	}
	return render(request, 'landing/landing.html', context)

def contactar(request):
	return HttpResponseRedirect(reverse('landing:home'))

def contacto(request):
	return render(request, 'landing/contacto.html')

landing/templates/landing/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name='description' content='{% block description %} {% endblock description %}'>
	<title>{% block title %} {% endblock title %}</title>
	<link href='http://fonts.googleapis.com/css?family=Roboto:400,400italic,500,500italic' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="{% static 'landing/css/base.css' %}">
	<script src="{% static 'landing/js/jquery.min.js' %}"></script>
	<script src="{% static 'landing/js/base.js' %}"></script>
	{% block statics %} {% endblock statics %}
</head>
<body>
	<div id="wrapper">

	{% block header %}
	<header>
		<h1>
			<a href="{% url 'landing:home' %}">
				<figure>
					<img src="{% static 'landing/img/logo.png' %}" alt="" width='300' height='130'>
				</figure>
			</a>		
		</h1>
		<nav>
			<ul>
				<div class="link-menu">
					<a href="{% url 'landing:home' %}"><li class="menu-title">Inicio</li></a>
				</div>
				<div class="link-menu accesorios">
					<a href="{% url 'accesorios:lista' %}"><li class="menu-title">Accesorios</li></a>
					<div id="menu-accesorios">
						<a href="{% url 'accesorios:lista_correas' %}"><li class="dropdown-child">Correas</li></a>
						<a href="{% url 'accesorios:lista_pecheras' %}"><li class="dropdown-child">Pecheras</li></a>
						<a href="{% url 'accesorios:lista_collares' %}"><li class="dropdown-child">Collares</li></a>
						<a href="{% url 'accesorios:lista_chalecos' %}"><li class="dropdown-child">Chalecos</li></a>
					</div>
				</div>
				<div class="link-menu juguetes">
					<a href="{% url 'juguetes:lista' %}"><li class="menu-title">Juguetes</li></a>
					<div id="menu-juguetes">
						<a href="{% url 'juguetes:lista_pelotas' %}"><li class="dropdown-child">Pelotas</li></a>
					</div>
				</div>
				<div class="link-menu">
					<a href="#"><li class="menu-title">Nosotros</li></a>
				</div>
				<div class="link-menu">
					<a href="{% url 'landing:contacto' %}"><li class="menu-title">Contacto</li></a>
				</div>
			</ul>
		</nav>
	</header>
	{% endblock header %}

	{% block banner%} 
	<section id="banner">
		<article class="banner-image" id="banner-1">
			<img src="{% static 'landing/img/banner-1.jpg' %}" alt="" width="900" height="280">
		</article>
		<article class="banner-image" id="banner-2">
			<img src="{% static 'landing/img/banner-2.jpg' %}" alt="" width="900" height="280">
		</article>
		<article class="banner-image" id="banner-3">
			<img src="{% static 'landing/img/banner-3.jpg' %}" alt="" width="900" height="280">
		</article>
		<div id="banner-bar">
			<div class="banner-bar-indicator" id="indicator-1"></div>
			<div class="banner-bar-indicator" id="indicator-2"></div>
			<div class="banner-bar-indicator" id="indicator-3"></div>
		</div>
	</section>
	{% endblock banner%}
	
	{% block content %} {% endblock content %}

	{% block footer %}
	<footer>
		<section>
			<article class="footer-section">
				<h3 class="footer-title">Productos</h3>
				<ul>
					<li><a href="{% url 'accesorios:lista_correas' %}">Correas</a></li>
					<li><a href="{% url 'accesorios:lista_pecheras' %}">Pecheras</a></li>
					<li><a href="{% url 'accesorios:lista_collares' %}">Collares</a></li>
					<li><a href="{% url 'accesorios:lista_chalecos' %}">Chalecos</a></li>
					<li><a href="{% url 'juguetes:lista_pelotas' %}">Pelotas</a></li>
				</ul>
			</article>
			<article class="footer-section">
				<h3 class="footer-title">Contactanos</h3>
				<form action="{% url 'landing:contactar' %}" method="post">
					{% csrf_token %}
					<input type="email" name="email" id="email">
					<input type="submit" value="">
					<p>Dejanos tu Email</p>
				</form>
			</article>
			<article class="footer-section">
				<a href="{% url 'landing:home' %}">
					<figure>
						<img src="{% static 'landing/img/logo.png' %}" alt="" width='250' height='110'>
					</figure>
				</a>	
				<p class="terms">Bogota - Colombia</p>
				<p class="terms">AnimalKingDog Todos los derechos reservados</p>	
			</article>
		</section>
	</footer>
	{% endblock footer %}

	</div>
</body>
</html>

landing/templates/landing/contacto.html
{% extends "landing/base.html" %}

{% load staticfiles %}

{% block description %}Descripcion del negocio{% endblock description %}

{% block title %}Contacto - AnimalKingDog{% endblock title %}

{% block statics %}
<link rel="stylesheet" href="{% static 'landing/css/contacto.css' %}">
<script src="{% static 'landing/js/contacto.js' %}"></script>
{% endblock statics %}

{% block banner %} {% endblock banner %}

{% block content %} 
<section id="container">
	<h2>Contacto</h2>
	<p>Hacemos ventas al por mayor, en bogota y en todo Colombia. Tambien tenemos puntos de venta en Bogota</p>
	<p>Por favor, dejanos tus datos para contactarnos contigo lo mas pronto posible</p>
	<form action="{% url 'landing:contactar' %}" method="post">
		{% csrf_token %}
		<label for="nombre">Nombre completo</label>
		<input type="text" name="nombre" id="nombre"><br>
		<label for="email">Correo electronico</label>
		<input type="email" name="email" id="email"><br>
		<p>Haz una consulta si deseas</p>
		<textarea name="consulta" id="consulta" rows="5" cols="70"></textarea><br>
		<input type="submit" value="Enviar">
	</form>
</section>
{% endblock content %}

landing/templates/landing/landing.html
{% extends "landing/base.html" %}

{% load staticfiles %}

{% block description %}Descripcion del negocio{% endblock description %}

{% block title %}AnimalKingDog{% endblock title %}

{% block statics %}
<link rel="stylesheet" href="{% static 'landing/css/landing.css' %}">
<script src="{% static 'landing/js/landing.js' %}"></script>
{% endblock statics %}

{% block content%} 
<section id="correas" class="product-list-container">
	<div class="product-list-separator"></div>
	<h2 class="product-list-title">Correas</h2>
	{% if not correas %}
	<h2>No hay correas para mostrar</h2>
	{% else%}
	{% for correa in correas %}
	<article class="product-container">
		<figure>
			<img src="{{correa.foto.url}}" alt="" width='220' height='220'>
		</figure>
		<a href="{% url 'accesorios:detalle_correa' correa.id %}">Detalles</a>
	</article>
	{% endfor %}
	{% endif %}
	<div class="visit-list-button">
		<a href="{% url 'accesorios:lista_correas' %}">Ver lista completa</a>
	</div>
</section>

<section id="pecheras" class="product-list-container">
	<div class="product-list-separator"></div>
	<h2 class="product-list-title">Pecheras</h2>
	{% if not pecheras %}
	<h2>No hay pecheras para mostrar</h2>
	{% else%}
	{% for pechera in pecheras %}
	<article class="product-container">
		<figure>
			<img src="{{pechera.foto.url}}" alt="" width='220' height='220'>
		</figure>
		<a href="{% url 'accesorios:detalle_pechera' pechera.id %}">Detalles</a>
	</article>
	{% endfor %}
	{% endif %}
	<div class="visit-list-button">
		<a href="{% url 'accesorios:lista_pecheras' %}">Ver lista completa</a>
	</div>
</section>

<section id="chalecos" class="product-list-container">
	<div class="product-list-separator"></div>
	<h2 class="product-list-title">Chalecos</h2>
	{% if not chalecos %}
	<h2>No hay chalecos para mostrar</h2>
	{% else%}
	{% for chaleco in chalecos %}
	<article class="product-container">
		<figure>
			<img src="{{chaleco.foto.url}}" alt="" width='220' height='220'>
		</figure>
		<a href="{% url 'accesorios:detalle_chaleco' chaleco.id %}">Detalles</a>
	</article>
	{% endfor %}
	{% endif %}
	<div class="visit-list-button">
		<a href="{% url 'accesorios:lista_chalecos' %}">Ver lista completa</a>
	</div>
</section>

<section id="collares" class="product-list-container">
	<div class="product-list-separator"></div>
	<h2 class="product-list-title">Collares</h2>
	{% if not collares %}
	<h2>No hay collares para mostrar</h2>
	{% else%}
	{% for collar in collares %}
	<article class="product-container">
		<figure>
			<img src="{{collar.foto.url}}" alt="" width='220' height='220'>
		</figure>
		<a href="{% url 'accesorios:detalle_collar' collar.id %}">Detalles</a>
	</article>
	{% endfor %}
	{% endif %}
	<div class="visit-list-button">
		<a href="{% url 'accesorios:lista_collares' %}">Ver lista completa</a>
	</div>
</section>

<section id="pelotas" class="product-list-container">
	<div class="product-list-separator"></div>
	<h2 class="product-list-title">Pelotas</h2>
	{% if not pelotas %}
	<h2>No hay pelotas para mostrar</h2>
	{% else%}
	{% for pelota in pelotas %}
	<article class="product-container">
		<figure>
			<img src="{{pelota.foto.url}}" alt="" width='220' height='220'>
		</figure>
		<a href="{% url 'juguetes:detalle_pelota' pelota.id %}">Detalles</a>
	</article>
	{% endfor %}
	{% endif %}
	<div class="visit-list-button">
		<a href="{% url 'juguetes:lista_pelotas' %}">Ver lista completa</a>
	</div>
</section>
{% endblock content%}